import tempfile
import unittest
from pathlib import Path

from render import RENDER_MARKER, _connection_suffix, prepare_engine_output


class RenderOutputSafetyTest(unittest.TestCase):
    def test_owned_directory_can_be_replaced_repeatedly(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            output = prepare_engine_output(root, "duckdb")
            (output / "generated.test").write_text("old", encoding="utf-8")

            replaced = prepare_engine_output(root, "duckdb")

            self.assertEqual(output, replaced)
            self.assertFalse((replaced / "generated.test").exists())
            self.assertTrue((replaced / RENDER_MARKER).is_file())

    def test_nonempty_unowned_directory_is_never_claimed(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            output = root / "duckdb"
            output.mkdir()
            unrelated = output / "keep.txt"
            unrelated.write_text("keep", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "not owned"):
                prepare_engine_output(root, "duckdb")

            self.assertEqual("keep", unrelated.read_text(encoding="utf-8"))
            self.assertFalse((output / RENDER_MARKER).exists())

    def test_symlink_output_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            target = root / "target"
            target.mkdir()
            (root / "duckdb").symlink_to(target, target_is_directory=True)

            with self.assertRaisesRegex(RuntimeError, "symlink"):
                prepare_engine_output(root, "duckdb")

    def test_invalid_marker_never_claims_existing_directory(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            output = root / "duckdb"
            output.mkdir()
            marker = output / RENDER_MARKER
            marker.write_text("not our marker\n", encoding="utf-8")
            sentinel = output / "keep.txt"
            sentinel.write_text("keep", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "marker is invalid"):
                prepare_engine_output(root, "duckdb")

            self.assertEqual("keep", sentinel.read_text(encoding="utf-8"))

    def test_symlink_marker_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            output = root / "duckdb"
            output.mkdir()
            real_marker = root / "marker"
            real_marker.write_text(
                "Generated by tests/spec/_lib/render.py; safe to replace.\n",
                encoding="utf-8",
            )
            (output / RENDER_MARKER).symlink_to(real_marker)

            with self.assertRaisesRegex(RuntimeError, "marker is invalid"):
                prepare_engine_output(root, "duckdb")

            self.assertTrue(output.is_dir())

    def test_regular_file_output_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            output = root / "duckdb"
            output.write_text("keep", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "not a directory"):
                prepare_engine_output(root, "duckdb")

            self.assertEqual("keep", output.read_text(encoding="utf-8"))

    def test_connection_name_is_restricted_to_identifier(self):
        self.assertEqual(" writer_2", _connection_suffix({"connection": "writer_2"}))
        with self.assertRaisesRegex(ValueError, "invalid"):
            _connection_suffix({"connection": "writer\nstatement ok"})


if __name__ == "__main__":
    unittest.main()
